steps:
#Copy the key file into the working environment
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://cloudbuild-bigquery-json/keyBigQuery.json', './server']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafiotripulaciones/$BRANCH_NAME:$SHORT_SHA', '-f', 'server/Dockerfile', './server']

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/desafiotripulaciones/$BRANCH_NAME:$SHORT_SHA']

# Deploy the Docker image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'backend-app'
  - '--image=gcr.io/$PROJECT_ID/desafiotripulaciones/$BRANCH_NAME:$SHORT_SHA'
  - '--region=europe-west1'
  - '--platform=managed'
  - '--port=5000'
  - '--allow-unauthenticated'
  - '--set-env-vars=USERS_TABLE=$$USERS_TABLE'

  secretEnv: [
    'USERS_TABLE']
availableSecrets:
  secretManager:
    - versionName: projects/476114540331/secrets/USERS_TABLE/versions/latest
      env: USERS_TABLE