require('dotenv').config()

const itemsQueries = {
    getSendas: `SELECT ID, LONGITUD, LATITUD, TIPO, NOMBRE, INICIO, FINAL, DISTANCIA_KM, LAT_LON_LIST FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'SENDA'`,
    getFuentes: `SELECT ID, DISTRITO, DIRECCION, LONGITUD, LATITUD, TIPO FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'FUENTE'`,
    getCentrosSalud: `SELECT ID, DIRECCION, LONGITUD, LATITUD, TIPO, NOMBRE FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'CENTRO DE SALUD'`,
    getParquesYJardines: `SELECT ID, DISTRITO, DIRECCION, LONGITUD, LATITUD, TIPO, NOMBRE, ACCESIBILIDAD, CONTENT_URL, BARRIO FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'ZONA VERDE'`,
    getPiscinas: `SELECT ID, DISTRITO, DIRECCION, LONGITUD, LATITUD, TIPO, NOMBRE, ACCESIBILIDAD, CONTENT_URL, BARRIO FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'PISCINA'`,
    getPolideportivos: `SELECT ID, DISTRITO, DIRECCION, LONGITUD, LATITUD, TIPO, NOMBRE, ACCESIBILIDAD, CONTENT_URL FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'INSTALACIÓN DEPORTIVA'`,
    getInfCiclista: `SELECT ID, DIRECCION, TIPO, DISTANCIA_KM, LAT_LON_LIST FROM ${process.env.ITEMS_TABLE} WHERE TIPO = 'INFRAESTRUCTURA CICLISTA'`,
}

module.exports = itemsQueries;